version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:23084
    volumes:
      - .:/app
    ports:
      - "23084:23084"
    depends_on:
      - db
    environment:
      - POSTGRES_NAME=inpc_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432

  db:
    image: postgis/postgis:13-3.1
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=inpc_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "24084:5432"

volumes:
  postgres_data:
