# Generated by Django 5.1.5 on 2025-01-23 08:40

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FamilleProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Famille de produits',
                'verbose_name_plural': 'Familles de produits',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='INPC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.DateField(verbose_name='Mois de calcul')),
                ('valeur', models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Valeur de l'INPC")),
                ('date_calcul', models.DateTimeField(auto_now_add=True, verbose_name='Date de calcul')),
            ],
            options={
                'verbose_name': 'INPC',
                'verbose_name_plural': 'INPC',
                'ordering': ['-mois'],
            },
        ),
        migrations.CreateModel(
            name='Moughataa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'Moughataa',
                'verbose_name_plural': 'Moughataas',
            },
        ),
        migrations.CreateModel(
            name='PanierProduits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Panier de produits',
                'verbose_name_plural': 'Paniers de produits',
            },
        ),
        migrations.CreateModel(
            name='Wilaya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'Wilaya',
                'verbose_name_plural': 'Wilayas',
            },
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('moughataa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communes', to='core.moughataa')),
            ],
            options={
                'verbose_name': 'Commune',
                'verbose_name_plural': 'Communes',
            },
        ),
        migrations.CreateModel(
            name='PointVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('adresse', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_vente', to='core.commune')),
            ],
            options={
                'verbose_name': 'Point de vente',
                'verbose_name_plural': 'Points de vente',
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('unite_mesure', models.CharField(max_length=50)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('famille', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produits', to='core.familleproduit')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ['famille', 'nom'],
            },
        ),
        migrations.AddField(
            model_name='moughataa',
            name='wilaya',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moughataas', to='core.wilaya'),
        ),
        migrations.CreateModel(
            name='PrixProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('date_releve', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_saisie', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('validé', 'Validé'), ('rejeté', 'Rejeté')], default='en_attente', max_length=20)),
                ('point_vente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prix', to='core.pointvente')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prix', to='core.produit')),
            ],
            options={
                'verbose_name': 'Prix de produit',
                'verbose_name_plural': 'Prix des produits',
                'indexes': [models.Index(fields=['date_releve'], name='core_prixpr_date_re_503c3d_idx'), models.Index(fields=['produit', 'date_releve'], name='core_prixpr_produit_35e5ab_idx')],
                'unique_together': {('produit', 'point_vente', 'date_releve')},
            },
        ),
        migrations.CreateModel(
            name='ProduitPanier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ponderation', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('date_debut', models.DateField(auto_now_add=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.produit')),
            ],
            options={
                'verbose_name': 'Produit du panier',
                'verbose_name_plural': 'Produits du panier',
                'indexes': [models.Index(fields=['produit', 'date_debut'], name='core_produi_produit_f17847_idx')],
            },
        ),
    ]
