# Generated by Django 5.1.5 on 2025-01-23 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='panierproduits',
            name='produits',
            field=models.ManyToManyField(related_name='paniers', through='core.ProduitPanier', to='core.produit'),
        ),
        migrations.AddField(
            model_name='produitpanier',
            name='panier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.panierproduits'),
        ),
    ]
