# Generated by Django 3.2.25 on 2025-02-02 21:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_panierproduits_produits_produitpanier_panier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produitpanier',
            name='date_debut',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
