# Generated by Django 5.1.4 on 2025-01-14 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=45, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=45, verbose_name='Nom')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Moughataa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=45, unique=True, verbose_name='Code')),
                ('label', models.CharField(max_length=45, verbose_name='Libellé')),
            ],
            options={
                'verbose_name': 'Moughataa',
                'verbose_name_plural': 'Moughataas',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=45, unique=True, verbose_name='Code')),
                ('name', models.CharField(default='Nom du produit par défaut', max_length=45, verbose_name='Nom')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('unit_measure', models.CharField(blank=True, max_length=45, null=True, verbose_name='Unité de mesure')),
            ],
        ),
        migrations.CreateModel(
            name='ProductFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Wilaya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=45, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=45, verbose_name='Nom')),
            ],
            options={
                'verbose_name': 'Wilaya',
                'verbose_name_plural': 'Wilayas',
            },
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=45, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=45, verbose_name='Nom')),
                ('moughataa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.moughataa', verbose_name='Moughataa associée')),
            ],
            options={
                'verbose_name': 'Commune',
                'verbose_name_plural': 'Communes',
            },
        ),
        migrations.CreateModel(
            name='PointOfSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=45, unique=True, verbose_name='Code')),
                ('type', models.CharField(max_length=45, verbose_name='Type')),
                ('gps_lat', models.FloatField(verbose_name='Latitude')),
                ('gps_lon', models.FloatField(verbose_name='Longitude')),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.commune', verbose_name='Commune')),
            ],
            options={
                'verbose_name': 'Point de vente',
                'verbose_name_plural': 'Points de vente',
            },
        ),
        migrations.CreateModel(
            name='CartProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(verbose_name='Poids')),
                ('date_from', models.DateField(verbose_name='Date de début')),
                ('date_to', models.DateField(verbose_name='Date de fin')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.cart', verbose_name='Panier')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.product', verbose_name='Produit')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='product_family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.productfamily', verbose_name='Famille de produit'),
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(verbose_name='Prix')),
                ('date_from', models.DateField(verbose_name='Date de début')),
                ('date_to', models.DateField(verbose_name='Date de fin')),
                ('point_of_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.pointofsale', verbose_name='Point de vente')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.product', verbose_name='Produit')),
            ],
        ),
        migrations.AddField(
            model_name='moughataa',
            name='wilaya',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.wilaya', verbose_name='Wilaya associée'),
        ),
    ]
