# Generated by Django 5.1.4 on 2025-01-13 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('price_unit', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.productfamily')),
            ],
        ),
    ]
