# Generated by Django 5.1.4 on 2025-01-13 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_panier'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='panier',
            options={'verbose_name': 'Panier', 'verbose_name_plural': 'Paniers'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Produit', 'verbose_name_plural': 'Produits'},
        ),
        migrations.AlterModelOptions(
            name='productfamily',
            options={'verbose_name': 'Famille de produit', 'verbose_name_plural': 'Familles de produits'},
        ),
        migrations.AlterField(
            model_name='panier',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Code du panier'),
        ),
        migrations.AlterField(
            model_name='panier',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='panier',
            name='label',
            field=models.CharField(max_length=100, verbose_name='Nom du panier'),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(max_length=10, unique=True, verbose_name='Code produit'),
        ),
        migrations.AlterField(
            model_name='product',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='pages.productfamily', verbose_name='Famille'),
        ),
        migrations.AlterField(
            model_name='product',
            name='label',
            field=models.CharField(max_length=200, verbose_name='Nom du produit'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_unit',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix unitaire'),
        ),
        migrations.AlterField(
            model_name='productfamily',
            name='label',
            field=models.CharField(max_length=255, verbose_name='Nom de la famille'),
        ),
    ]
