# Generated by Django 5.1.4 on 2025-01-13 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_product_options_remove_product_price_unit_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productfamily',
            options={},
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_measure',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productfamily',
            name='label',
            field=models.CharField(max_length=255),
        ),
    ]
