# Generated by Django 5.1.4 on 2025-01-13 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_productfamily_options_alter_product_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=45, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=45, verbose_name='Nom')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='CartProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(verbose_name='Poids')),
                ('date_from', models.DateField(verbose_name='Date de début')),
                ('date_to', models.DateField(verbose_name='Date de fin')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.cart', verbose_name='Panier')),
            ],
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=45, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=45, verbose_name='Nom')),
            ],
            options={
                'verbose_name': 'Commune',
                'verbose_name_plural': 'Communes',
            },
        ),
        migrations.CreateModel(
            name='Moughataa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=45, unique=True, verbose_name='Code')),
                ('label', models.CharField(max_length=45, verbose_name='Libellé')),
            ],
            options={
                'verbose_name': 'Moughataa',
                'verbose_name_plural': 'Moughataas',
            },
        ),
        migrations.CreateModel(
            name='PointOfSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=45, unique=True, verbose_name='Code')),
                ('type', models.CharField(max_length=45, verbose_name='Type')),
                ('gps_lat', models.FloatField(verbose_name='Latitude')),
                ('gps_lon', models.FloatField(verbose_name='Longitude')),
            ],
            options={
                'verbose_name': 'Point de vente',
                'verbose_name_plural': 'Points de vente',
            },
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(verbose_name='Prix')),
                ('date_from', models.DateField(verbose_name='Date de début')),
                ('date_to', models.DateField(verbose_name='Date de fin')),
            ],
        ),
        migrations.CreateModel(
            name='Wilaya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=45, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=45, verbose_name='Nom')),
            ],
            options={
                'verbose_name': 'Wilaya',
                'verbose_name_plural': 'Wilayas',
            },
        ),
        migrations.DeleteModel(
            name='Panier',
        ),
        migrations.RemoveField(
            model_name='product',
            name='family',
        ),
        migrations.RemoveField(
            model_name='product',
            name='label',
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default='Nom du produit par défaut', max_length=45, verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_family',
            field=models.ForeignKey(default='Default', on_delete=django.db.models.deletion.CASCADE, to='pages.productfamily', verbose_name='Famille de produit'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(max_length=45, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_measure',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Unité de mesure'),
        ),
        migrations.AlterField(
            model_name='productfamily',
            name='label',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.product', verbose_name='Produit'),
        ),
        migrations.AddField(
            model_name='commune',
            name='moughataa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.moughataa', verbose_name='Moughataa associée'),
        ),
        migrations.AddField(
            model_name='pointofsale',
            name='commune',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.commune', verbose_name='Commune'),
        ),
        migrations.AddField(
            model_name='productprice',
            name='point_of_sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.pointofsale', verbose_name='Point de vente'),
        ),
        migrations.AddField(
            model_name='productprice',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.product', verbose_name='Produit'),
        ),
        migrations.AddField(
            model_name='moughataa',
            name='wilaya',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.wilaya', verbose_name='Wilaya associée'),
        ),
    ]
